// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

export interface AcceptInviteRequest {
	token: string
}

export interface AcceptInviteResponse {
	organization: Organization
	message: string
}

export interface AdminListSubscriptionsRequest {
}
export interface AdminListSubscriptionsRequestParams {
	page?: number
	pageSize?: number
	status?: string
}

export interface AdminListSubscriptionsResponse {
	subscriptions: Array<AdminSubscription>
	totalCount: number
	page: number
	pageSize: number
}

export interface AdminListUsersRequest {
}
export interface AdminListUsersRequestParams {
	page?: number
	pageSize?: number
	search?: string
}

export interface AdminListUsersResponse {
	users: Array<AdminUser>
	totalCount: number
	page: number
	pageSize: number
}

export interface AdminStatsResponse {
	totalUsers: number
	activeSubscriptions: number
	trialSubscriptions: number
	monthlyRevenue: number
	currency: string
	newUsersToday: number
	newUsersThisWeek: number
	newUsersThisMonth: number
}

export interface AdminSubscription {
	id: string
	userId: string
	userEmail: string
	planName: string
	status: string
	amount: number
	currency: string
	interval: string
	createdAt: string
}

export interface AdminUser {
	id: string
	email: string
	name: string
	plan: string
	status: string
	createdAt: string
}

export interface AuthConfigResponse {
	googleEnabled: boolean
	githubEnabled: boolean
}

export interface BillingRecord {
	id: string
	amount: number
	currency: string
	status: string
	description?: string
	invoiceDate: string
	paidAt?: string
	invoicePdfUrl?: string
	hostedInvoiceUrl?: string
}

export interface CancelSubscriptionRequest {
	cancelAtPeriodEnd?: boolean
}

export interface CancelSubscriptionResponse {
	message: string
	cancelledAt?: string
	effectiveAt?: string
}

export interface ChangePasswordRequest {
	currentPassword: string
	newPassword: string
}

export interface CheckFeatureRequest {
	feature: string
}

export interface CheckFeatureResponse {
	hasAccess: boolean
	feature: string
	planName: string
	message?: string
}

export interface CreateBillingPortalResponse {
	portalUrl: string
}

export interface CreateCheckoutRequest {
	planName: string
	billingCycle?: string
}

export interface CreateCheckoutResponse {
	checkoutUrl: string
}

export interface CreateOrganizationRequest {
	name: string
	slug?: string
	logoUrl?: string
}

export interface CreateOrganizationResponse {
	organization: Organization
}

export interface DeleteAccountRequest {
	password: string
}

export interface DeleteNotificationRequest {
}
export interface DeleteNotificationRequestParams {
}

export interface DeleteOrganizationRequest {
}
export interface DeleteOrganizationRequestParams {
}

export interface DisconnectOAuthRequest {
}
export interface DisconnectOAuthRequestParams {
}

export interface EmailVerificationRequest {
	token: string
}

export interface Empty {
}

export interface ForgotPasswordRequest {
	email: string
}

export interface GetInviteByTokenRequest {
}
export interface GetInviteByTokenRequestParams {
}

export interface GetInviteByTokenResponse {
	invite: OrganizationInvite
	organizationName: string
	organizationSlug: string
}

export interface GetOAuthUrlRequest {
}
export interface GetOAuthUrlRequestParams {
	redirectUrl?: string
}

export interface GetOAuthUrlResponse {
	url: string
	state: string
}

export interface GetOrganizationRequest {
}
export interface GetOrganizationRequestParams {
}

export interface GetOrganizationResponse {
	organization: Organization
	role: string
}

export interface GetPreferencesResponse {
	preferences: UserPreferences
}

export interface GetSubscriptionResponse {
	subscription: UserSubscription
	plan: SubscriptionPlan
}

export interface GetUnreadCountResponse {
	count: number
}

export interface GetUsageStatsResponse {
	stats: UsageStats
}

export interface GetUserResponse {
	user: User
}

export interface HealthResponse {
	status: string
	version: string
	timestamp: string
}

export interface InviteMemberRequest {
	email: string
	role?: string
}
export interface InviteMemberRequestParams {
}

export interface InviteMemberResponse {
	invite: OrganizationInvite
}

export interface LeaveOrganizationRequest {
}
export interface LeaveOrganizationRequestParams {
}

export interface ListBillingHistoryRequest {
}
export interface ListBillingHistoryRequestParams {
	page?: number
	pageSize?: number
}

export interface ListBillingHistoryResponse {
	records: Array<BillingRecord>
	totalCount: number
	page: number
	pageSize: number
}

export interface ListInvitesRequest {
}
export interface ListInvitesRequestParams {
}

export interface ListInvitesResponse {
	invites: Array<OrganizationInvite>
}

export interface ListMembersRequest {
}
export interface ListMembersRequestParams {
}

export interface ListMembersResponse {
	members: Array<OrganizationMember>
}

export interface ListNotificationsRequest {
}
export interface ListNotificationsRequestParams {
	page?: number
	pageSize?: number
	unread?: boolean
}

export interface ListNotificationsResponse {
	notifications: Array<Notification>
	unreadCount: number
	totalCount: number
}

export interface ListOAuthProvidersResponse {
	providers: Array<OAuthProvider>
}

export interface ListOrganizationsResponse {
	organizations: Array<Organization>
}

export interface ListPlansResponse {
	plans: Array<SubscriptionPlan>
}

export interface LoginRequest {
	email: string
	password: string
}

export interface LoginResponse {
	token: string
	refreshToken: string
	expiresAt: number
	checkoutUrl?: string
}

export interface MarkNotificationReadRequest {
}
export interface MarkNotificationReadRequestParams {
}

export interface MessageResponse {
	message: string
}

export interface Notification {
	id: string
	type: string
	title: string
	body?: string
	actionUrl?: string
	icon?: string
	readAt?: string
	createdAt: string
}

export interface OAuthLoginRequest {
	code: string
	state?: string
}
export interface OAuthLoginRequestParams {
}

export interface OAuthLoginResponse {
	token: string
	refreshToken: string
	expiresAt: number
	isNewUser: boolean
}

export interface OAuthProvider {
	name: string
	connected: boolean
	email?: string
}

export interface Organization {
	id: string
	name: string
	slug: string
	logoUrl?: string
	ownerId: string
	createdAt: string
	updatedAt: string
}

export interface OrganizationInvite {
	id: string
	email: string
	role: string
	inviterName: string
	inviterEmail: string
	organizationName?: string
	expiresAt: string
	createdAt: string
}

export interface OrganizationMember {
	id: string
	userId: string
	email: string
	name: string
	avatarUrl?: string
	role: string
	joinedAt: string
}

export interface RefreshTokenRequest {
	refreshToken: string
}

export interface RefreshTokenResponse {
	token: string
	refreshToken: string
	expiresAt: number
}

export interface RegisterRequest {
	email: string
	password: string
	name: string
	plan?: string
}

export interface RemoveMemberRequest {
}
export interface RemoveMemberRequestParams {
}

export interface ResendVerificationRequest {
	email: string
}

export interface ResetPasswordRequest {
	token: string
	newPassword: string
}

export interface RevokeInviteRequest {
}
export interface RevokeInviteRequestParams {
}

export interface SubscriptionPlan {
	id: string
	name: string
	displayName: string
	description: string
	price: number
	currency: string
	interval: string
	features: Array<string>
}

export interface SwitchOrganizationRequest {
	organizationId: string
}

export interface UpdateMemberRoleRequest {
	role: string
}
export interface UpdateMemberRoleRequestParams {
}

export interface UpdateOrganizationRequest {
	name?: string
	slug?: string
	logoUrl?: string
}
export interface UpdateOrganizationRequestParams {
}

export interface UpdatePreferencesRequest {
	emailNotifications?: boolean
	marketingEmails?: boolean
	timezone?: string
	language?: string
	theme?: string
}

export interface UpdateUserRequest {
	name?: string
	avatarUrl?: string
}

export interface UsageStats {
	periodStart: string
	periodEnd: string
	meters: { [key: string]: number }
}

export interface User {
	id: string
	email: string
	name: string
	avatarUrl?: string
	emailVerified: boolean
	createdAt: string
	updatedAt: string
}

export interface UserPreferences {
	emailNotifications: boolean
	marketingEmails: boolean
	timezone: string
	language: string
	theme: string
}

export interface UserSubscription {
	id: string
	planId: string
	planName: string
	status: string
	billingCycle: string
	currentPeriodStart?: string
	currentPeriodEnd?: string
	trialEnd?: string
	cancelAtPeriodEnd: boolean
}

