// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

export interface AcceptInviteRequest {
	token: string
}

export interface AcceptInviteResponse {
	organization: Organization
	message: string
}

export interface AgentConnectRequest {
	agentId: string
}

export interface AgentConnectResponse {
	connected: boolean
	agentId: string
	orgId: string
}

export interface AgentInfo {
	agentId: string
	orgId: string
	userId: string
	connected: boolean
	createdAt: string
}

export interface AgentStatusRequest {
}
export interface AgentStatusRequestParams {
}

export interface AgentStatusResponse {
	agentId: string
	orgId: string
	connected: boolean
	uptime: number
}

export interface AuthConfigResponse {
	googleEnabled: boolean
	githubEnabled: boolean
}

export interface ChangePasswordRequest {
	currentPassword: string
	newPassword: string
}

export interface CreateAdminRequest {
	email: string
	password: string
	name: string
}

export interface CreateAdminResponse {
	token: string
	refreshToken: string
	expiresAt: number
	user: User
}

export interface CreateOrganizationRequest {
	name: string
	slug?: string
	logoUrl?: string
}

export interface CreateOrganizationResponse {
	organization: Organization
}

export interface DeleteAccountRequest {
	password: string
}

export interface DeleteNotificationRequest {
}
export interface DeleteNotificationRequestParams {
}

export interface DeleteOrganizationRequest {
}
export interface DeleteOrganizationRequestParams {
}

export interface DisconnectOAuthRequest {
}
export interface DisconnectOAuthRequestParams {
}

export interface EmailVerificationRequest {
	token: string
}

export interface Empty {
}

export interface ForgotPasswordRequest {
	email: string
}

export interface GetInviteByTokenRequest {
}
export interface GetInviteByTokenRequestParams {
}

export interface GetInviteByTokenResponse {
	invite: OrganizationInvite
	organizationName: string
	organizationSlug: string
}

export interface GetOAuthUrlRequest {
}
export interface GetOAuthUrlRequestParams {
	redirectUrl?: string
}

export interface GetOAuthUrlResponse {
	url: string
	state: string
}

export interface GetOrganizationRequest {
}
export interface GetOrganizationRequestParams {
}

export interface GetOrganizationResponse {
	organization: Organization
	role: string
}

export interface GetPreferencesResponse {
	preferences: UserPreferences
}

export interface GetUnreadCountResponse {
	count: number
}

export interface GetUserResponse {
	user: User
}

export interface HealthResponse {
	status: string
	version: string
	timestamp: string
}

export interface InviteMemberRequest {
	email: string
	role?: string
}
export interface InviteMemberRequestParams {
}

export interface InviteMemberResponse {
	invite: OrganizationInvite
}

export interface LeaveOrganizationRequest {
}
export interface LeaveOrganizationRequestParams {
}

export interface ListAgentsRequest {
}
export interface ListAgentsRequestParams {
}

export interface ListAgentsResponse {
	agents: Array<AgentInfo>
	total: number
}

export interface ListInvitesRequest {
}
export interface ListInvitesRequestParams {
}

export interface ListInvitesResponse {
	invites: Array<OrganizationInvite>
}

export interface ListMembersRequest {
}
export interface ListMembersRequestParams {
}

export interface ListMembersResponse {
	members: Array<OrganizationMember>
}

export interface ListNotificationsRequest {
}
export interface ListNotificationsRequestParams {
	page?: number
	pageSize?: number
	unread?: boolean
}

export interface ListNotificationsResponse {
	notifications: Array<Notification>
	unreadCount: number
	totalCount: number
}

export interface ListOAuthProvidersResponse {
	providers: Array<OAuthProvider>
}

export interface ListOrganizationsResponse {
	organizations: Array<Organization>
}

export interface LoginRequest {
	email: string
	password: string
}

export interface LoginResponse {
	token: string
	refreshToken: string
	expiresAt: number
}

export interface MarkNotificationReadRequest {
}
export interface MarkNotificationReadRequestParams {
}

export interface MessageResponse {
	message: string
}

export interface Notification {
	id: string
	type: string
	title: string
	body?: string
	actionUrl?: string
	icon?: string
	readAt?: string
	createdAt: string
}

export interface OAuthLoginRequest {
	code: string
	state?: string
}
export interface OAuthLoginRequestParams {
}

export interface OAuthLoginResponse {
	token: string
	refreshToken: string
	expiresAt: number
	isNewUser: boolean
}

export interface OAuthProvider {
	name: string
	connected: boolean
	email?: string
}

export interface Organization {
	id: string
	name: string
	slug: string
	logoUrl?: string
	ownerId: string
	createdAt: string
	updatedAt: string
}

export interface OrganizationInvite {
	id: string
	email: string
	role: string
	inviterName: string
	inviterEmail: string
	organizationName?: string
	expiresAt: string
	createdAt: string
}

export interface OrganizationMember {
	id: string
	userId: string
	email: string
	name: string
	avatarUrl?: string
	role: string
	joinedAt: string
}

export interface RefreshTokenRequest {
	refreshToken: string
}

export interface RefreshTokenResponse {
	token: string
	refreshToken: string
	expiresAt: number
}

export interface RegisterRequest {
	email: string
	password: string
	name: string
}

export interface RemoveMemberRequest {
}
export interface RemoveMemberRequestParams {
}

export interface ResendVerificationRequest {
	email: string
}

export interface ResetPasswordRequest {
	token: string
	newPassword: string
}

export interface RevokeInviteRequest {
}
export interface RevokeInviteRequestParams {
}

export interface SetupStatusResponse {
	setupRequired: boolean
	hasAdmin: boolean
}

export interface SwitchOrganizationRequest {
	organizationId: string
}

export interface UpdateMemberRoleRequest {
	role: string
}
export interface UpdateMemberRoleRequestParams {
}

export interface UpdateOrganizationRequest {
	name?: string
	slug?: string
	logoUrl?: string
}
export interface UpdateOrganizationRequestParams {
}

export interface UpdatePreferencesRequest {
	emailNotifications?: boolean
	marketingEmails?: boolean
	timezone?: string
	language?: string
	theme?: string
}

export interface UpdateUserRequest {
	name?: string
	avatarUrl?: string
}

export interface User {
	id: string
	email: string
	name: string
	avatarUrl?: string
	emailVerified: boolean
	createdAt: string
	updatedAt: string
}

export interface UserPreferences {
	emailNotifications: boolean
	marketingEmails: boolean
	timezone: string
	language: string
	theme: string
}

