// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AcceptInviteRequest struct {
	Token string `json:"token"`
}

type AcceptInviteResponse struct {
	Organization Organization `json:"organization"`
	Message      string       `json:"message"`
}

type AdminListSubscriptionsRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
}

type AdminListSubscriptionsResponse struct {
	Subscriptions []AdminSubscription `json:"subscriptions"`
	TotalCount    int                 `json:"totalCount"`
	Page          int                 `json:"page"`
	PageSize      int                 `json:"pageSize"`
}

type AdminListUsersRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Search   string `form:"search,optional"`
}

type AdminListUsersResponse struct {
	Users      []AdminUser `json:"users"`
	TotalCount int         `json:"totalCount"`
	Page       int         `json:"page"`
	PageSize   int         `json:"pageSize"`
}

type AdminStatsResponse struct {
	TotalUsers          int    `json:"totalUsers"`
	ActiveSubscriptions int    `json:"activeSubscriptions"`
	TrialSubscriptions  int    `json:"trialSubscriptions"`
	MonthlyRevenue      int    `json:"monthlyRevenue"`
	Currency            string `json:"currency"`
	NewUsersToday       int    `json:"newUsersToday"`
	NewUsersThisWeek    int    `json:"newUsersThisWeek"`
	NewUsersThisMonth   int    `json:"newUsersThisMonth"`
}

type AdminSubscription struct {
	Id        string `json:"id"`
	UserId    string `json:"userId"`
	UserEmail string `json:"userEmail"`
	PlanName  string `json:"planName"`
	Status    string `json:"status"`
	Amount    int    `json:"amount"`
	Currency  string `json:"currency"`
	Interval  string `json:"interval"`
	CreatedAt string `json:"createdAt"`
}

type AdminUser struct {
	Id        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	Plan      string `json:"plan"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type AuthConfigResponse struct {
	GoogleEnabled bool `json:"googleEnabled"`
	GitHubEnabled bool `json:"githubEnabled"`
}

type BillingRecord struct {
	Id               string `json:"id"`
	Amount           int    `json:"amount"`
	Currency         string `json:"currency"`
	Status           string `json:"status"`
	Description      string `json:"description,omitempty"`
	InvoiceDate      string `json:"invoiceDate"`
	PaidAt           string `json:"paidAt,omitempty"`
	InvoicePdfUrl    string `json:"invoicePdfUrl,omitempty"`
	HostedInvoiceUrl string `json:"hostedInvoiceUrl,omitempty"`
}

type CancelSubscriptionRequest struct {
	CancelAtPeriodEnd bool `json:"cancelAtPeriodEnd,optional"`
}

type CancelSubscriptionResponse struct {
	Message     string `json:"message"`
	CancelledAt string `json:"cancelledAt,omitempty"`
	EffectiveAt string `json:"effectiveAt,omitempty"`
}

type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type CheckFeatureRequest struct {
	Feature string `json:"feature"`
}

type CheckFeatureResponse struct {
	HasAccess bool   `json:"hasAccess"`
	Feature   string `json:"feature"`
	PlanName  string `json:"planName"`
	Message   string `json:"message,omitempty"`
}

type CreateBillingPortalResponse struct {
	PortalUrl string `json:"portalUrl"`
}

type CreateCheckoutRequest struct {
	PlanName     string `json:"planName"`
	BillingCycle string `json:"billingCycle,optional"`
}

type CreateCheckoutResponse struct {
	CheckoutUrl string `json:"checkoutUrl"`
}

type CreateOrganizationRequest struct {
	Name    string `json:"name"`
	Slug    string `json:"slug,optional"`
	LogoUrl string `json:"logoUrl,optional"`
}

type CreateOrganizationResponse struct {
	Organization Organization `json:"organization"`
}

type DeleteAccountRequest struct {
	Password string `json:"password"`
}

type DeleteNotificationRequest struct {
	Id string `path:"id"`
}

type DeleteOrganizationRequest struct {
	Id string `path:"id"`
}

type DisconnectOAuthRequest struct {
	Provider string `path:"provider"`
}

type EmailVerificationRequest struct {
	Token string `json:"token"`
}

type Empty struct {
}

type ForgotPasswordRequest struct {
	Email string `json:"email"`
}

type GetInviteByTokenRequest struct {
	Token string `path:"token"`
}

type GetInviteByTokenResponse struct {
	Invite           OrganizationInvite `json:"invite"`
	OrganizationName string             `json:"organizationName"`
	OrganizationSlug string             `json:"organizationSlug"`
}

type GetOAuthUrlRequest struct {
	Provider    string `path:"provider"`
	RedirectUrl string `form:"redirectUrl,optional"`
}

type GetOAuthUrlResponse struct {
	Url   string `json:"url"`
	State string `json:"state"`
}

type GetOrganizationRequest struct {
	Id string `path:"id"`
}

type GetOrganizationResponse struct {
	Organization Organization `json:"organization"`
	Role         string       `json:"role"`
}

type GetPreferencesResponse struct {
	Preferences UserPreferences `json:"preferences"`
}

type GetSubscriptionResponse struct {
	Subscription UserSubscription `json:"subscription"`
	Plan         SubscriptionPlan `json:"plan"`
}

type GetUnreadCountResponse struct {
	Count int `json:"count"`
}

type GetUsageStatsResponse struct {
	Stats UsageStats `json:"stats"`
}

type GetUserResponse struct {
	User User `json:"user"`
}

type HealthResponse struct {
	Status    string `json:"status"`
	Version   string `json:"version"`
	Timestamp string `json:"timestamp"`
}

type InviteMemberRequest struct {
	Id    string `path:"id"`
	Email string `json:"email"`
	Role  string `json:"role,optional"`
}

type InviteMemberResponse struct {
	Invite OrganizationInvite `json:"invite"`
}

type LeaveOrganizationRequest struct {
	Id string `path:"id"`
}

type ListBillingHistoryRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type ListBillingHistoryResponse struct {
	Records    []BillingRecord `json:"records"`
	TotalCount int             `json:"totalCount"`
	Page       int             `json:"page"`
	PageSize   int             `json:"pageSize"`
}

type ListInvitesRequest struct {
	Id string `path:"id"`
}

type ListInvitesResponse struct {
	Invites []OrganizationInvite `json:"invites"`
}

type ListMembersRequest struct {
	Id string `path:"id"`
}

type ListMembersResponse struct {
	Members []OrganizationMember `json:"members"`
}

type ListNotificationsRequest struct {
	Page     int  `form:"page,optional"`
	PageSize int  `form:"pageSize,optional"`
	Unread   bool `form:"unread,optional"`
}

type ListNotificationsResponse struct {
	Notifications []Notification `json:"notifications"`
	UnreadCount   int            `json:"unreadCount"`
	TotalCount    int            `json:"totalCount"`
}

type ListOAuthProvidersResponse struct {
	Providers []OAuthProvider `json:"providers"`
}

type ListOrganizationsResponse struct {
	Organizations []Organization `json:"organizations"`
}

type ListPlansResponse struct {
	Plans []SubscriptionPlan `json:"plans"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
	CheckoutUrl  string `json:"checkoutUrl,optional"`
}

type MarkNotificationReadRequest struct {
	Id string `path:"id"`
}

type MessageResponse struct {
	Message string `json:"message"`
}

type Notification struct {
	Id        string `json:"id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Body      string `json:"body,omitempty"`
	ActionUrl string `json:"actionUrl,omitempty"`
	Icon      string `json:"icon,omitempty"`
	ReadAt    string `json:"readAt,omitempty"`
	CreatedAt string `json:"createdAt"`
}

type OAuthLoginRequest struct {
	Provider string `path:"provider"`
	Code     string `json:"code"`
	State    string `json:"state,optional"`
}

type OAuthLoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
	IsNewUser    bool   `json:"isNewUser"`
}

type OAuthProvider struct {
	Name      string `json:"name"`
	Connected bool   `json:"connected"`
	Email     string `json:"email,omitempty"`
}

type Organization struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	LogoUrl   string `json:"logoUrl,omitempty"`
	OwnerId   string `json:"ownerId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type OrganizationInvite struct {
	Id               string `json:"id"`
	Email            string `json:"email"`
	Role             string `json:"role"`
	InviterName      string `json:"inviterName"`
	InviterEmail     string `json:"inviterEmail"`
	OrganizationName string `json:"organizationName,omitempty"`
	ExpiresAt        string `json:"expiresAt"`
	CreatedAt        string `json:"createdAt"`
}

type OrganizationMember struct {
	Id        string `json:"id"`
	UserId    string `json:"userId"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	AvatarUrl string `json:"avatarUrl,omitempty"`
	Role      string `json:"role"`
	JoinedAt  string `json:"joinedAt"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
	Plan     string `json:"plan,optional"`
}

type RemoveMemberRequest struct {
	OrgId  string `path:"orgId"`
	UserId string `path:"userId"`
}

type ResendVerificationRequest struct {
	Email string `json:"email"`
}

type ResetPasswordRequest struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type RevokeInviteRequest struct {
	OrgId    string `path:"orgId"`
	InviteId string `path:"inviteId"`
}

type SubscriptionPlan struct {
	Id          string   `json:"id"`
	Name        string   `json:"name"`
	DisplayName string   `json:"displayName"`
	Description string   `json:"description"`
	Price       int      `json:"price"`
	Currency    string   `json:"currency"`
	Interval    string   `json:"interval"`
	Features    []string `json:"features"`
}

type SwitchOrganizationRequest struct {
	OrganizationId string `json:"organizationId"`
}

type UpdateMemberRoleRequest struct {
	OrgId  string `path:"orgId"`
	UserId string `path:"userId"`
	Role   string `json:"role"`
}

type UpdateOrganizationRequest struct {
	Id      string `path:"id"`
	Name    string `json:"name,optional"`
	Slug    string `json:"slug,optional"`
	LogoUrl string `json:"logoUrl,optional"`
}

type UpdatePreferencesRequest struct {
	EmailNotifications bool   `json:"emailNotifications,optional"`
	MarketingEmails    bool   `json:"marketingEmails,optional"`
	Timezone           string `json:"timezone,optional"`
	Language           string `json:"language,optional"`
	Theme              string `json:"theme,optional"`
}

type UpdateUserRequest struct {
	Name      string `json:"name,optional"`
	AvatarUrl string `json:"avatarUrl,optional"`
}

type UsageStats struct {
	PeriodStart string         `json:"periodStart"`
	PeriodEnd   string         `json:"periodEnd"`
	Meters      map[string]int `json:"meters"`
}

type User struct {
	Id            string `json:"id"`
	Email         string `json:"email"`
	Name          string `json:"name"`
	AvatarUrl     string `json:"avatarUrl,omitempty"`
	EmailVerified bool   `json:"emailVerified"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type UserPreferences struct {
	EmailNotifications bool   `json:"emailNotifications"`
	MarketingEmails    bool   `json:"marketingEmails"`
	Timezone           string `json:"timezone"`
	Language           string `json:"language"`
	Theme              string `json:"theme"`
}

type UserSubscription struct {
	Id                 string `json:"id"`
	PlanId             string `json:"planId"`
	PlanName           string `json:"planName"`
	Status             string `json:"status"`
	BillingCycle       string `json:"billingCycle"`
	CurrentPeriodStart string `json:"currentPeriodStart,omitempty"`
	CurrentPeriodEnd   string `json:"currentPeriodEnd,omitempty"`
	TrialEnd           string `json:"trialEnd,omitempty"`
	CancelAtPeriodEnd  bool   `json:"cancelAtPeriodEnd"`
}
