// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type AcceptInviteRequest struct {
	Token string `json:"token"`
}

type AcceptInviteResponse struct {
	Organization Organization `json:"organization"`
	Message      string       `json:"message"`
}

type AgentConnectRequest struct {
	AgentId string `json:"agentId"`
}

type AgentConnectResponse struct {
	Connected bool   `json:"connected"`
	AgentId   string `json:"agentId"`
	OrgId     string `json:"orgId"`
}

type AgentInfo struct {
	AgentId   string `json:"agentId"`
	OrgId     string `json:"orgId"`
	UserId    string `json:"userId"`
	Connected bool   `json:"connected"`
	CreatedAt string `json:"createdAt"`
}

type AgentStatusRequest struct {
	AgentId string `path:"agentId"`
}

type AgentStatusResponse struct {
	AgentId   string `json:"agentId"`
	OrgId     string `json:"orgId"`
	Connected bool   `json:"connected"`
	Uptime    int64  `json:"uptime"`
}

type AuthConfigResponse struct {
	GoogleEnabled bool `json:"googleEnabled"`
	GitHubEnabled bool `json:"githubEnabled"`
}

type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type CreateAdminRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type CreateAdminResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
	User         User   `json:"user"`
}

type CreateOrganizationRequest struct {
	Name    string `json:"name"`
	Slug    string `json:"slug,optional"`
	LogoUrl string `json:"logoUrl,optional"`
}

type CreateOrganizationResponse struct {
	Organization Organization `json:"organization"`
}

type DeleteAccountRequest struct {
	Password string `json:"password"`
}

type DeleteNotificationRequest struct {
	Id string `path:"id"`
}

type DeleteOrganizationRequest struct {
	Id string `path:"id"`
}

type DisconnectOAuthRequest struct {
	Provider string `path:"provider"`
}

type EmailVerificationRequest struct {
	Token string `json:"token"`
}

type Empty struct {
}

type ForgotPasswordRequest struct {
	Email string `json:"email"`
}

type GetInviteByTokenRequest struct {
	Token string `path:"token"`
}

type GetInviteByTokenResponse struct {
	Invite           OrganizationInvite `json:"invite"`
	OrganizationName string             `json:"organizationName"`
	OrganizationSlug string             `json:"organizationSlug"`
}

type GetOAuthUrlRequest struct {
	Provider    string `path:"provider"`
	RedirectUrl string `form:"redirectUrl,optional"`
}

type GetOAuthUrlResponse struct {
	Url   string `json:"url"`
	State string `json:"state"`
}

type GetOrganizationRequest struct {
	Id string `path:"id"`
}

type GetOrganizationResponse struct {
	Organization Organization `json:"organization"`
	Role         string       `json:"role"`
}

type GetPreferencesResponse struct {
	Preferences UserPreferences `json:"preferences"`
}

type GetUnreadCountResponse struct {
	Count int `json:"count"`
}

type GetUserResponse struct {
	User User `json:"user"`
}

type HealthResponse struct {
	Status    string `json:"status"`
	Version   string `json:"version"`
	Timestamp string `json:"timestamp"`
}

type InviteMemberRequest struct {
	Id    string `path:"id"`
	Email string `json:"email"`
	Role  string `json:"role,optional"`
}

type InviteMemberResponse struct {
	Invite OrganizationInvite `json:"invite"`
}

type LeaveOrganizationRequest struct {
	Id string `path:"id"`
}

type ListAgentsRequest struct {
	OrgId string `path:"orgId,optional"`
}

type ListAgentsResponse struct {
	Agents []AgentInfo `json:"agents"`
	Total  int         `json:"total"`
}

type ListInvitesRequest struct {
	Id string `path:"id"`
}

type ListInvitesResponse struct {
	Invites []OrganizationInvite `json:"invites"`
}

type ListMembersRequest struct {
	Id string `path:"id"`
}

type ListMembersResponse struct {
	Members []OrganizationMember `json:"members"`
}

type ListNotificationsRequest struct {
	Page     int  `form:"page,optional"`
	PageSize int  `form:"pageSize,optional"`
	Unread   bool `form:"unread,optional"`
}

type ListNotificationsResponse struct {
	Notifications []Notification `json:"notifications"`
	UnreadCount   int            `json:"unreadCount"`
	TotalCount    int            `json:"totalCount"`
}

type ListOAuthProvidersResponse struct {
	Providers []OAuthProvider `json:"providers"`
}

type ListOrganizationsResponse struct {
	Organizations []Organization `json:"organizations"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
}

type MarkNotificationReadRequest struct {
	Id string `path:"id"`
}

type MessageResponse struct {
	Message string `json:"message"`
}

type Notification struct {
	Id        string `json:"id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Body      string `json:"body,omitempty"`
	ActionUrl string `json:"actionUrl,omitempty"`
	Icon      string `json:"icon,omitempty"`
	ReadAt    string `json:"readAt,omitempty"`
	CreatedAt string `json:"createdAt"`
}

type OAuthLoginRequest struct {
	Provider string `path:"provider"`
	Code     string `json:"code"`
	State    string `json:"state,optional"`
}

type OAuthLoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
	IsNewUser    bool   `json:"isNewUser"`
}

type OAuthProvider struct {
	Name      string `json:"name"`
	Connected bool   `json:"connected"`
	Email     string `json:"email,omitempty"`
}

type Organization struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	LogoUrl   string `json:"logoUrl,omitempty"`
	OwnerId   string `json:"ownerId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type OrganizationInvite struct {
	Id               string `json:"id"`
	Email            string `json:"email"`
	Role             string `json:"role"`
	InviterName      string `json:"inviterName"`
	InviterEmail     string `json:"inviterEmail"`
	OrganizationName string `json:"organizationName,omitempty"`
	ExpiresAt        string `json:"expiresAt"`
	CreatedAt        string `json:"createdAt"`
}

type OrganizationMember struct {
	Id        string `json:"id"`
	UserId    string `json:"userId"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	AvatarUrl string `json:"avatarUrl,omitempty"`
	Role      string `json:"role"`
	JoinedAt  string `json:"joinedAt"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type RemoveMemberRequest struct {
	OrgId  string `path:"orgId"`
	UserId string `path:"userId"`
}

type ResendVerificationRequest struct {
	Email string `json:"email"`
}

type ResetPasswordRequest struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type RevokeInviteRequest struct {
	OrgId    string `path:"orgId"`
	InviteId string `path:"inviteId"`
}

type SetupStatusResponse struct {
	SetupRequired bool `json:"setupRequired"`
	HasAdmin      bool `json:"hasAdmin"`
}

type SwitchOrganizationRequest struct {
	OrganizationId string `json:"organizationId"`
}

type UpdateMemberRoleRequest struct {
	OrgId  string `path:"orgId"`
	UserId string `path:"userId"`
	Role   string `json:"role"`
}

type UpdateOrganizationRequest struct {
	Id      string `path:"id"`
	Name    string `json:"name,optional"`
	Slug    string `json:"slug,optional"`
	LogoUrl string `json:"logoUrl,optional"`
}

type UpdatePreferencesRequest struct {
	EmailNotifications bool   `json:"emailNotifications,optional"`
	MarketingEmails    bool   `json:"marketingEmails,optional"`
	Timezone           string `json:"timezone,optional"`
	Language           string `json:"language,optional"`
	Theme              string `json:"theme,optional"`
}

type UpdateUserRequest struct {
	Name      string `json:"name,optional"`
	AvatarUrl string `json:"avatarUrl,optional"`
}

type User struct {
	Id            string `json:"id"`
	Email         string `json:"email"`
	Name          string `json:"name"`
	AvatarUrl     string `json:"avatarUrl,omitempty"`
	EmailVerified bool   `json:"emailVerified"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type UserPreferences struct {
	EmailNotifications bool   `json:"emailNotifications"`
	MarketingEmails    bool   `json:"marketingEmails"`
	Timezone           string `json:"timezone"`
	Language           string `json:"language"`
	Theme              string `json:"theme"`
}
