// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	agent "gobot/internal/handler/agent"
	auth "gobot/internal/handler/auth"
	notification "gobot/internal/handler/notification"
	oauth "gobot/internal/handler/oauth"
	organization "gobot/internal/handler/organization"
	setup "gobot/internal/handler/setup"
	user "gobot/internal/handler/user"
	"gobot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Health check endpoint
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthCheckHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List connected agents for organization
				Method:  http.MethodGet,
				Path:    "/agents",
				Handler: agent.ListAgentsHandler(serverCtx),
			},
			{
				// Get agent status
				Method:  http.MethodGet,
				Path:    "/agents/:agentId/status",
				Handler: agent.GetAgentStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get auth configuration (OAuth providers enabled)
				Method:  http.MethodGet,
				Path:    "/auth/config",
				Handler: auth.GetAuthConfigHandler(serverCtx),
			},
			{
				// Request password reset
				Method:  http.MethodPost,
				Path:    "/auth/forgot-password",
				Handler: auth.ForgotPasswordHandler(serverCtx),
			},
			{
				// User login
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// Refresh authentication token
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				// Register new user
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				// Resend email verification
				Method:  http.MethodPost,
				Path:    "/auth/resend-verification",
				Handler: auth.ResendVerificationHandler(serverCtx),
			},
			{
				// Reset password with token
				Method:  http.MethodPost,
				Path:    "/auth/reset-password",
				Handler: auth.ResetPasswordHandler(serverCtx),
			},
			{
				// Verify email address with token
				Method:  http.MethodPost,
				Path:    "/auth/verify-email",
				Handler: auth.VerifyEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List user notifications
				Method:  http.MethodGet,
				Path:    "/notifications",
				Handler: notification.ListNotificationsHandler(serverCtx),
			},
			{
				// Delete notification
				Method:  http.MethodDelete,
				Path:    "/notifications/:id",
				Handler: notification.DeleteNotificationHandler(serverCtx),
			},
			{
				// Mark notification as read
				Method:  http.MethodPut,
				Path:    "/notifications/:id/read",
				Handler: notification.MarkNotificationReadHandler(serverCtx),
			},
			{
				// Mark all notifications as read
				Method:  http.MethodPut,
				Path:    "/notifications/read-all",
				Handler: notification.MarkAllNotificationsReadHandler(serverCtx),
			},
			{
				// Get unread notification count
				Method:  http.MethodGet,
				Path:    "/notifications/unread-count",
				Handler: notification.GetUnreadCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// OAuth callback - exchange code for tokens
				Method:  http.MethodPost,
				Path:    "/oauth/:provider/callback",
				Handler: oauth.OAuthCallbackHandler(serverCtx),
			},
			{
				// Get OAuth authorization URL
				Method:  http.MethodGet,
				Path:    "/oauth/:provider/url",
				Handler: oauth.GetOAuthUrlHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Disconnect OAuth provider
				Method:  http.MethodDelete,
				Path:    "/oauth/:provider",
				Handler: oauth.DisconnectOAuthHandler(serverCtx),
			},
			{
				// List connected OAuth providers
				Method:  http.MethodGet,
				Path:    "/oauth/providers",
				Handler: oauth.ListOAuthProvidersHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Create a new organization
				Method:  http.MethodPost,
				Path:    "/organizations",
				Handler: organization.CreateOrganizationHandler(serverCtx),
			},
			{
				// List user's organizations
				Method:  http.MethodGet,
				Path:    "/organizations",
				Handler: organization.ListOrganizationsHandler(serverCtx),
			},
			{
				// Get organization by ID
				Method:  http.MethodGet,
				Path:    "/organizations/:id",
				Handler: organization.GetOrganizationHandler(serverCtx),
			},
			{
				// Update organization
				Method:  http.MethodPut,
				Path:    "/organizations/:id",
				Handler: organization.UpdateOrganizationHandler(serverCtx),
			},
			{
				// Delete organization
				Method:  http.MethodDelete,
				Path:    "/organizations/:id",
				Handler: organization.DeleteOrganizationHandler(serverCtx),
			},
			{
				// Invite member to organization
				Method:  http.MethodPost,
				Path:    "/organizations/:id/invites",
				Handler: organization.InviteMemberHandler(serverCtx),
			},
			{
				// List pending invites
				Method:  http.MethodGet,
				Path:    "/organizations/:id/invites",
				Handler: organization.ListInvitesHandler(serverCtx),
			},
			{
				// Leave organization
				Method:  http.MethodPost,
				Path:    "/organizations/:id/leave",
				Handler: organization.LeaveOrganizationHandler(serverCtx),
			},
			{
				// List organization members
				Method:  http.MethodGet,
				Path:    "/organizations/:id/members",
				Handler: organization.ListMembersHandler(serverCtx),
			},
			{
				// Revoke invite
				Method:  http.MethodDelete,
				Path:    "/organizations/:orgId/invites/:inviteId",
				Handler: organization.RevokeInviteHandler(serverCtx),
			},
			{
				// Update member role
				Method:  http.MethodPut,
				Path:    "/organizations/:orgId/members/:userId",
				Handler: organization.UpdateMemberRoleHandler(serverCtx),
			},
			{
				// Remove member from organization
				Method:  http.MethodDelete,
				Path:    "/organizations/:orgId/members/:userId",
				Handler: organization.RemoveMemberHandler(serverCtx),
			},
			{
				// Accept organization invite
				Method:  http.MethodPost,
				Path:    "/organizations/invites/accept",
				Handler: organization.AcceptInviteHandler(serverCtx),
			},
			{
				// Switch current organization
				Method:  http.MethodPost,
				Path:    "/organizations/switch",
				Handler: organization.SwitchOrganizationHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get invite details by token
				Method:  http.MethodGet,
				Path:    "/organizations/invites/:token",
				Handler: organization.GetInviteByTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Create the first admin user (only works when no admin exists)
				Method:  http.MethodPost,
				Path:    "/setup/admin",
				Handler: setup.CreateAdminHandler(serverCtx),
			},
			{
				// Check if setup is required (no admin exists)
				Method:  http.MethodGet,
				Path:    "/setup/status",
				Handler: setup.SetupStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get current user profile
				Method:  http.MethodGet,
				Path:    "/user/me",
				Handler: user.GetCurrentUserHandler(serverCtx),
			},
			{
				// Update current user profile
				Method:  http.MethodPut,
				Path:    "/user/me",
				Handler: user.UpdateCurrentUserHandler(serverCtx),
			},
			{
				// Delete current user account
				Method:  http.MethodDelete,
				Path:    "/user/me",
				Handler: user.DeleteAccountHandler(serverCtx),
			},
			{
				// Change password for authenticated user
				Method:  http.MethodPost,
				Path:    "/user/me/change-password",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
			{
				// Get user preferences
				Method:  http.MethodGet,
				Path:    "/user/me/preferences",
				Handler: user.GetPreferencesHandler(serverCtx),
			},
			{
				// Update user preferences
				Method:  http.MethodPut,
				Path:    "/user/me/preferences",
				Handler: user.UpdatePreferencesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
