// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leads.sql

package db

import (
	"context"
	"database/sql"
)

const countLeads = `-- name: CountLeads :one
SELECT COUNT(*) as count
FROM leads
WHERE (?1 IS NULL OR status = ?1)
`

func (q *Queries) CountLeads(ctx context.Context, filterStatus interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLeads, filterStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (
    id, email, name, source, status, metadata, created_at
) VALUES (
    ?1, ?2, ?3, ?4,
    COALESCE(?5, 'pending'), ?6,
    strftime('%s', 'now')
)
RETURNING id, email, name, source, status, metadata, created_at
`

type CreateLeadParams struct {
	ID       string         `json:"id"`
	Email    string         `json:"email"`
	Name     sql.NullString `json:"name"`
	Source   sql.NullString `json:"source"`
	Status   interface{}    `json:"status"`
	Metadata sql.NullString `json:"metadata"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRowContext(ctx, createLead,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Source,
		arg.Status,
		arg.Metadata,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Source,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLead = `-- name: DeleteLead :exec
DELETE FROM leads WHERE id = ?1
`

func (q *Queries) DeleteLead(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLead, id)
	return err
}

const getLeadByEmail = `-- name: GetLeadByEmail :one
SELECT id, email, name, source, status, metadata, created_at
FROM leads
WHERE LOWER(email) = LOWER(?1)
LIMIT 1
`

func (q *Queries) GetLeadByEmail(ctx context.Context, email string) (Lead, error) {
	row := q.db.QueryRowContext(ctx, getLeadByEmail, email)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Source,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getLeadByID = `-- name: GetLeadByID :one
SELECT id, email, name, source, status, metadata, created_at
FROM leads
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetLeadByID(ctx context.Context, id string) (Lead, error) {
	row := q.db.QueryRowContext(ctx, getLeadByID, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Source,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listLeads = `-- name: ListLeads :many
SELECT id, email, name, source, status, metadata, created_at
FROM leads
WHERE (?1 IS NULL OR status = ?1)
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListLeadsParams struct {
	FilterStatus interface{} `json:"filter_status"`
	PageOffset   int64       `json:"page_offset"`
	PageSize     int64       `json:"page_size"`
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.QueryContext(ctx, listLeads, arg.FilterStatus, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lead
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Source,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeadStatus = `-- name: UpdateLeadStatus :exec
UPDATE leads
SET status = ?1
WHERE id = ?2
`

type UpdateLeadStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLeadStatus, arg.Status, arg.ID)
	return err
}
