// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_oauth.sql

package db

import (
	"context"
	"database/sql"
)

const createMCPOAuthClient = `-- name: CreateMCPOAuthClient :one


INSERT INTO mcp_oauth_clients (id, client_id, client_secret_hash, name, description, redirect_uris, scopes, is_confidential)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, client_id, client_secret_hash, name, description, redirect_uris, scopes, is_confidential, created_at, updated_at
`

type CreateMCPOAuthClientParams struct {
	ID               string         `json:"id"`
	ClientID         string         `json:"client_id"`
	ClientSecretHash string         `json:"client_secret_hash"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	RedirectUris     string         `json:"redirect_uris"`
	Scopes           sql.NullString `json:"scopes"`
	IsConfidential   sql.NullInt64  `json:"is_confidential"`
}

// MCP OAuth queries for Dynamic Client Registration and OAuth flows
// =============================================================================
// OAuth Clients
// =============================================================================
func (q *Queries) CreateMCPOAuthClient(ctx context.Context, arg CreateMCPOAuthClientParams) (McpOauthClient, error) {
	row := q.db.QueryRowContext(ctx, createMCPOAuthClient,
		arg.ID,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.Name,
		arg.Description,
		arg.RedirectUris,
		arg.Scopes,
		arg.IsConfidential,
	)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.Scopes,
		&i.IsConfidential,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMCPOAuthCode = `-- name: CreateMCPOAuthCode :one

INSERT INTO mcp_oauth_codes (id, client_id, user_id, code_hash, redirect_uri, scopes, code_challenge, code_challenge_method, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, client_id, user_id, code_hash, redirect_uri, scopes, code_challenge, code_challenge_method, expires_at, used_at, created_at
`

type CreateMCPOAuthCodeParams struct {
	ID                  string         `json:"id"`
	ClientID            string         `json:"client_id"`
	UserID              string         `json:"user_id"`
	CodeHash            string         `json:"code_hash"`
	RedirectUri         string         `json:"redirect_uri"`
	Scopes              string         `json:"scopes"`
	CodeChallenge       sql.NullString `json:"code_challenge"`
	CodeChallengeMethod sql.NullString `json:"code_challenge_method"`
	ExpiresAt           string         `json:"expires_at"`
}

// =============================================================================
// OAuth Authorization Codes
// =============================================================================
func (q *Queries) CreateMCPOAuthCode(ctx context.Context, arg CreateMCPOAuthCodeParams) (McpOauthCode, error) {
	row := q.db.QueryRowContext(ctx, createMCPOAuthCode,
		arg.ID,
		arg.ClientID,
		arg.UserID,
		arg.CodeHash,
		arg.RedirectUri,
		arg.Scopes,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	var i McpOauthCode
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.CodeHash,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMCPOAuthToken = `-- name: CreateMCPOAuthToken :one

INSERT INTO mcp_oauth_tokens (id, client_id, user_id, access_token_hash, refresh_token_hash, scopes, expires_at, refresh_expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, client_id, user_id, access_token_hash, refresh_token_hash, scopes, expires_at, refresh_expires_at, revoked_at, created_at
`

type CreateMCPOAuthTokenParams struct {
	ID               string         `json:"id"`
	ClientID         string         `json:"client_id"`
	UserID           string         `json:"user_id"`
	AccessTokenHash  string         `json:"access_token_hash"`
	RefreshTokenHash sql.NullString `json:"refresh_token_hash"`
	Scopes           string         `json:"scopes"`
	ExpiresAt        string         `json:"expires_at"`
	RefreshExpiresAt sql.NullString `json:"refresh_expires_at"`
}

// =============================================================================
// OAuth Tokens
// =============================================================================
func (q *Queries) CreateMCPOAuthToken(ctx context.Context, arg CreateMCPOAuthTokenParams) (McpOauthToken, error) {
	row := q.db.QueryRowContext(ctx, createMCPOAuthToken,
		arg.ID,
		arg.ClientID,
		arg.UserID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.Scopes,
		arg.ExpiresAt,
		arg.RefreshExpiresAt,
	)
	var i McpOauthToken
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPOAuthClientByClientID = `-- name: GetMCPOAuthClientByClientID :one
SELECT id, client_id, client_secret_hash, name, description, redirect_uris, scopes, is_confidential, created_at, updated_at FROM mcp_oauth_clients
WHERE client_id = ?
`

func (q *Queries) GetMCPOAuthClientByClientID(ctx context.Context, clientID string) (McpOauthClient, error) {
	row := q.db.QueryRowContext(ctx, getMCPOAuthClientByClientID, clientID)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.Scopes,
		&i.IsConfidential,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPOAuthClientByID = `-- name: GetMCPOAuthClientByID :one
SELECT id, client_id, client_secret_hash, name, description, redirect_uris, scopes, is_confidential, created_at, updated_at FROM mcp_oauth_clients
WHERE id = ?
`

func (q *Queries) GetMCPOAuthClientByID(ctx context.Context, id string) (McpOauthClient, error) {
	row := q.db.QueryRowContext(ctx, getMCPOAuthClientByID, id)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.Scopes,
		&i.IsConfidential,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPOAuthCodeByHash = `-- name: GetMCPOAuthCodeByHash :one
SELECT
    c.id, c.client_id, c.user_id, c.code_hash, c.redirect_uri, c.scopes, c.code_challenge, c.code_challenge_method, c.expires_at, c.used_at, c.created_at,
    cl.client_id as oauth_client_id
FROM mcp_oauth_codes c
JOIN mcp_oauth_clients cl ON c.client_id = cl.id
WHERE c.code_hash = ? AND c.used_at IS NULL
`

type GetMCPOAuthCodeByHashRow struct {
	ID                  string         `json:"id"`
	ClientID            string         `json:"client_id"`
	UserID              string         `json:"user_id"`
	CodeHash            string         `json:"code_hash"`
	RedirectUri         string         `json:"redirect_uri"`
	Scopes              string         `json:"scopes"`
	CodeChallenge       sql.NullString `json:"code_challenge"`
	CodeChallengeMethod sql.NullString `json:"code_challenge_method"`
	ExpiresAt           string         `json:"expires_at"`
	UsedAt              sql.NullString `json:"used_at"`
	CreatedAt           int64          `json:"created_at"`
	OauthClientID       string         `json:"oauth_client_id"`
}

func (q *Queries) GetMCPOAuthCodeByHash(ctx context.Context, codeHash string) (GetMCPOAuthCodeByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getMCPOAuthCodeByHash, codeHash)
	var i GetMCPOAuthCodeByHashRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.CodeHash,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.OauthClientID,
	)
	return i, err
}

const getMCPOAuthTokenByAccessHash = `-- name: GetMCPOAuthTokenByAccessHash :one
SELECT id, client_id, user_id, access_token_hash, refresh_token_hash, scopes, expires_at, refresh_expires_at, revoked_at, created_at FROM mcp_oauth_tokens
WHERE access_token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetMCPOAuthTokenByAccessHash(ctx context.Context, accessTokenHash string) (McpOauthToken, error) {
	row := q.db.QueryRowContext(ctx, getMCPOAuthTokenByAccessHash, accessTokenHash)
	var i McpOauthToken
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPOAuthTokenByRefreshHash = `-- name: GetMCPOAuthTokenByRefreshHash :one
SELECT id, client_id, user_id, access_token_hash, refresh_token_hash, scopes, expires_at, refresh_expires_at, revoked_at, created_at FROM mcp_oauth_tokens
WHERE refresh_token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetMCPOAuthTokenByRefreshHash(ctx context.Context, refreshTokenHash sql.NullString) (McpOauthToken, error) {
	row := q.db.QueryRowContext(ctx, getMCPOAuthTokenByRefreshHash, refreshTokenHash)
	var i McpOauthToken
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMCPOAuthCodeUsed = `-- name: MarkMCPOAuthCodeUsed :exec
UPDATE mcp_oauth_codes
SET used_at = datetime('now')
WHERE id = ?
`

func (q *Queries) MarkMCPOAuthCodeUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markMCPOAuthCodeUsed, id)
	return err
}

const revokeMCPOAuthToken = `-- name: RevokeMCPOAuthToken :exec
UPDATE mcp_oauth_tokens
SET revoked_at = datetime('now')
WHERE id = ?
`

func (q *Queries) RevokeMCPOAuthToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeMCPOAuthToken, id)
	return err
}

const revokeUserMCPOAuthTokens = `-- name: RevokeUserMCPOAuthTokens :exec
UPDATE mcp_oauth_tokens
SET revoked_at = datetime('now')
WHERE user_id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeUserMCPOAuthTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeUserMCPOAuthTokens, userID)
	return err
}
