// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) as count FROM notifications
WHERE user_id = ?1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, user_id, type, title, body, action_url, icon, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, strftime('%s', 'now'))
RETURNING id, user_id, type, title, body, action_url, icon, read_at, created_at
`

type CreateNotificationParams struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Type      string         `json:"type"`
	Title     string         `json:"title"`
	Body      sql.NullString `json:"body"`
	ActionUrl sql.NullString `json:"action_url"`
	Icon      sql.NullString `json:"icon"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.ActionUrl,
		arg.Icon,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ActionUrl,
		&i.Icon,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = ?1 AND user_id = ?2
`

type DeleteNotificationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications WHERE created_at < ?1
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, before int64) error {
	_, err := q.db.ExecContext(ctx, deleteOldNotifications, before)
	return err
}

const getInappNotificationsSetting = `-- name: GetInappNotificationsSetting :one
SELECT inapp_notifications FROM user_preferences WHERE user_id = ?1 LIMIT 1
`

func (q *Queries) GetInappNotificationsSetting(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getInappNotificationsSetting, userID)
	var inapp_notifications int64
	err := row.Scan(&inapp_notifications)
	return inapp_notifications, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, type, title, body, action_url, icon, read_at, created_at FROM notifications WHERE id = ?1 AND user_id = ?2 LIMIT 1
`

type GetNotificationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotification, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ActionUrl,
		&i.Icon,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, type, title, body, action_url, icon, read_at, created_at FROM notifications
WHERE user_id = ?1 AND read_at IS NULL
ORDER BY created_at DESC
LIMIT ?2
`

type ListUnreadNotificationsParams struct {
	UserID   string `json:"user_id"`
	PageSize int64  `json:"page_size"`
}

func (q *Queries) ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadNotifications, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ActionUrl,
			&i.Icon,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, user_id, type, title, body, action_url, icon, read_at, created_at FROM notifications
WHERE user_id = ?1
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListUserNotificationsParams struct {
	UserID     string `json:"user_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUserNotifications, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ActionUrl,
			&i.Icon,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = strftime('%s', 'now')
WHERE user_id = ?1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = strftime('%s', 'now')
WHERE id = ?1 AND user_id = ?2
`

type MarkNotificationReadParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const setInappNotificationsSetting = `-- name: SetInappNotificationsSetting :exec
UPDATE user_preferences
SET inapp_notifications = ?1,
    updated_at = strftime('%s', 'now')
WHERE user_id = ?2
`

type SetInappNotificationsSettingParams struct {
	Enabled int64  `json:"enabled"`
	UserID  string `json:"user_id"`
}

func (q *Queries) SetInappNotificationsSetting(ctx context.Context, arg SetInappNotificationsSettingParams) error {
	_, err := q.db.ExecContext(ctx, setInappNotificationsSetting, arg.Enabled, arg.UserID)
	return err
}
