// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"
	"database/sql"
)

const createOAuthConnection = `-- name: CreateOAuthConnection :one
INSERT INTO oauth_connections (id, user_id, provider, provider_user_id, email, name, avatar_url, access_token, refresh_token, expires_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, strftime('%s', 'now'), strftime('%s', 'now'))
RETURNING id, user_id, provider, provider_user_id, email, name, avatar_url, access_token, refresh_token, expires_at, created_at, updated_at
`

type CreateOAuthConnectionParams struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	Provider       string         `json:"provider"`
	ProviderUserID string         `json:"provider_user_id"`
	Email          sql.NullString `json:"email"`
	Name           sql.NullString `json:"name"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	AccessToken    sql.NullString `json:"access_token"`
	RefreshToken   sql.NullString `json:"refresh_token"`
	ExpiresAt      sql.NullInt64  `json:"expires_at"`
}

func (q *Queries) CreateOAuthConnection(ctx context.Context, arg CreateOAuthConnectionParams) (OauthConnection, error) {
	row := q.db.QueryRowContext(ctx, createOAuthConnection,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i OauthConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserFromOAuth = `-- name: CreateUserFromOAuth :one
INSERT INTO users (id, email, password_hash, name, avatar_url, email_verified, created_at, updated_at)
VALUES (?1, ?2, '', ?3, ?4, 1, strftime('%s', 'now'), strftime('%s', 'now'))
RETURNING id, email, password_hash, name, avatar_url, email_verified, email_verify_token, email_verify_expires, password_reset_token, password_reset_expires, created_at, updated_at, role
`

type CreateUserFromOAuthParams struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) CreateUserFromOAuth(ctx context.Context, arg CreateUserFromOAuthParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserFromOAuth,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const deleteOAuthConnection = `-- name: DeleteOAuthConnection :exec
DELETE FROM oauth_connections WHERE id = ?1 AND user_id = ?2
`

type DeleteOAuthConnectionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteOAuthConnection(ctx context.Context, arg DeleteOAuthConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthConnection, arg.ID, arg.UserID)
	return err
}

const deleteOAuthConnectionByProvider = `-- name: DeleteOAuthConnectionByProvider :exec
DELETE FROM oauth_connections WHERE user_id = ?1 AND provider = ?2
`

type DeleteOAuthConnectionByProviderParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteOAuthConnectionByProvider(ctx context.Context, arg DeleteOAuthConnectionByProviderParams) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthConnectionByProvider, arg.UserID, arg.Provider)
	return err
}

const getOAuthConnectionByProvider = `-- name: GetOAuthConnectionByProvider :one
SELECT id, user_id, provider, provider_user_id, email, name, avatar_url, access_token, refresh_token, expires_at, created_at, updated_at FROM oauth_connections
WHERE provider = ?1 AND provider_user_id = ?2
LIMIT 1
`

type GetOAuthConnectionByProviderParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthConnectionByProvider(ctx context.Context, arg GetOAuthConnectionByProviderParams) (OauthConnection, error) {
	row := q.db.QueryRowContext(ctx, getOAuthConnectionByProvider, arg.Provider, arg.ProviderUserID)
	var i OauthConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthConnectionByUserAndProvider = `-- name: GetOAuthConnectionByUserAndProvider :one
SELECT id, user_id, provider, provider_user_id, email, name, avatar_url, access_token, refresh_token, expires_at, created_at, updated_at FROM oauth_connections
WHERE user_id = ?1 AND provider = ?2
LIMIT 1
`

type GetOAuthConnectionByUserAndProviderParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetOAuthConnectionByUserAndProvider(ctx context.Context, arg GetOAuthConnectionByUserAndProviderParams) (OauthConnection, error) {
	row := q.db.QueryRowContext(ctx, getOAuthConnectionByUserAndProvider, arg.UserID, arg.Provider)
	var i OauthConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserOAuthConnections = `-- name: ListUserOAuthConnections :many
SELECT id, user_id, provider, provider_user_id, email, name, avatar_url, access_token, refresh_token, expires_at, created_at, updated_at FROM oauth_connections
WHERE user_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListUserOAuthConnections(ctx context.Context, userID string) ([]OauthConnection, error) {
	rows, err := q.db.QueryContext(ctx, listUserOAuthConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthConnection
	for rows.Next() {
		var i OauthConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthConnection = `-- name: UpdateOAuthConnection :exec
UPDATE oauth_connections
SET email = COALESCE(?1, email),
    name = COALESCE(?2, name),
    avatar_url = COALESCE(?3, avatar_url),
    access_token = COALESCE(?4, access_token),
    refresh_token = COALESCE(?5, refresh_token),
    expires_at = COALESCE(?6, expires_at),
    updated_at = strftime('%s', 'now')
WHERE id = ?7
`

type UpdateOAuthConnectionParams struct {
	Email        sql.NullString `json:"email"`
	Name         sql.NullString `json:"name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	AccessToken  sql.NullString `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	ExpiresAt    sql.NullInt64  `json:"expires_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateOAuthConnection(ctx context.Context, arg UpdateOAuthConnectionParams) error {
	_, err := q.db.ExecContext(ctx, updateOAuthConnection,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
