// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"
	"database/sql"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions
SET status = ?1,
    cancel_at_period_end = ?2,
    updated_at = strftime('%s', 'now')
WHERE user_id = ?3
`

type CancelSubscriptionParams struct {
	Status            string `json:"status"`
	CancelAtPeriodEnd int64  `json:"cancel_at_period_end"`
	UserID            string `json:"user_id"`
}

func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, cancelSubscription, arg.Status, arg.CancelAtPeriodEnd, arg.UserID)
	return err
}

const countActiveSubscriptions = `-- name: CountActiveSubscriptions :one

SELECT COUNT(*) as total FROM subscriptions WHERE status = 'active' AND plan_id != 'free'
`

// Admin queries
func (q *Queries) CountActiveSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSubscriptions)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSubscriptionsFiltered = `-- name: CountSubscriptionsFiltered :one
SELECT COUNT(*) as total
FROM subscriptions s
WHERE (?1 = '' OR s.status = ?1)
`

func (q *Queries) CountSubscriptionsFiltered(ctx context.Context, statusFilter interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptionsFiltered, statusFilter)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTrialSubscriptions = `-- name: CountTrialSubscriptions :one
SELECT COUNT(*) as total FROM subscriptions WHERE status = 'trialing'
`

func (q *Queries) CountTrialSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrialSubscriptions)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    id, user_id, plan_id, status, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, user_id, stripe_customer_id, stripe_subscription_id, plan_id, status,
          current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	PlanID string `json:"plan_id"`
	Status string `json:"status"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.ID,
		arg.UserID,
		arg.PlanID,
		arg.Status,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE user_id = ?1
`

func (q *Queries) DeleteSubscription(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, userID)
	return err
}

const downgradeToFree = `-- name: DowngradeToFree :exec
UPDATE subscriptions
SET plan_id = 'free',
    status = 'active',
    stripe_subscription_id = NULL,
    cancel_at_period_end = 0,
    updated_at = strftime('%s', 'now')
WHERE stripe_subscription_id = ?1
`

func (q *Queries) DowngradeToFree(ctx context.Context, stripeSubscriptionID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, downgradeToFree, stripeSubscriptionID)
	return err
}

const getSubscriptionByStripeCustomerID = `-- name: GetSubscriptionByStripeCustomerID :one
SELECT id, user_id, stripe_customer_id, stripe_subscription_id, plan_id, status,
       current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
FROM subscriptions
WHERE stripe_customer_id = ?1
LIMIT 1
`

func (q *Queries) GetSubscriptionByStripeCustomerID(ctx context.Context, stripeCustomerID sql.NullString) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByStripeCustomerID, stripeCustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByStripeSubID = `-- name: GetSubscriptionByStripeSubID :one
SELECT id, user_id, stripe_customer_id, stripe_subscription_id, plan_id, status,
       current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
FROM subscriptions
WHERE stripe_subscription_id = ?1
LIMIT 1
`

func (q *Queries) GetSubscriptionByStripeSubID(ctx context.Context, stripeSubscriptionID sql.NullString) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByStripeSubID, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, stripe_customer_id, stripe_subscription_id, plan_id, status,
       current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
FROM subscriptions
WHERE user_id = ?1
LIMIT 1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionsPaginated = `-- name: ListSubscriptionsPaginated :many
SELECT s.id, s.user_id, u.email as user_email, s.plan_id, s.status,
       s.stripe_subscription_id, s.current_period_start, s.current_period_end,
       s.cancel_at_period_end, s.created_at, s.updated_at
FROM subscriptions s
JOIN users u ON s.user_id = u.id
WHERE (?1 = '' OR s.status = ?1)
ORDER BY s.created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListSubscriptionsPaginatedParams struct {
	StatusFilter interface{} `json:"status_filter"`
	PageOffset   int64       `json:"page_offset"`
	PageSize     int64       `json:"page_size"`
}

type ListSubscriptionsPaginatedRow struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	UserEmail            string         `json:"user_email"`
	PlanID               string         `json:"plan_id"`
	Status               string         `json:"status"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	CurrentPeriodStart   sql.NullInt64  `json:"current_period_start"`
	CurrentPeriodEnd     sql.NullInt64  `json:"current_period_end"`
	CancelAtPeriodEnd    int64          `json:"cancel_at_period_end"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
}

func (q *Queries) ListSubscriptionsPaginated(ctx context.Context, arg ListSubscriptionsPaginatedParams) ([]ListSubscriptionsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsPaginated, arg.StatusFilter, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsPaginatedRow
	for rows.Next() {
		var i ListSubscriptionsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.PlanID,
			&i.Status,
			&i.StripeSubscriptionID,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtPeriodEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET status = ?1,
    current_period_start = ?2,
    current_period_end = ?3,
    cancel_at_period_end = ?4,
    updated_at = strftime('%s', 'now')
WHERE stripe_subscription_id = ?5
`

type UpdateSubscriptionStatusParams struct {
	Status               string         `json:"status"`
	PeriodStart          sql.NullInt64  `json:"period_start"`
	PeriodEnd            sql.NullInt64  `json:"period_end"`
	CancelAtPeriodEnd    int64          `json:"cancel_at_period_end"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatus,
		arg.Status,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.StripeSubscriptionID,
	)
	return err
}

const updateSubscriptionStripeIDs = `-- name: UpdateSubscriptionStripeIDs :exec
UPDATE subscriptions
SET stripe_customer_id = ?1,
    stripe_subscription_id = ?2,
    plan_id = ?3,
    status = ?4,
    updated_at = strftime('%s', 'now')
WHERE user_id = ?5
`

type UpdateSubscriptionStripeIDsParams struct {
	StripeCustomerID     sql.NullString `json:"stripe_customer_id"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	PlanID               string         `json:"plan_id"`
	Status               string         `json:"status"`
	UserID               string         `json:"user_id"`
}

func (q *Queries) UpdateSubscriptionStripeIDs(ctx context.Context, arg UpdateSubscriptionStripeIDsParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStripeIDs,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.PlanID,
		arg.Status,
		arg.UserID,
	)
	return err
}
