// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END as found
FROM users WHERE LOWER(email) = LOWER(?1)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExists, email)
	var found int64
	err := row.Scan(&found)
	return found, err
}

const countUsers = `-- name: CountUsers :one

SELECT COUNT(*) as total FROM users
`

// Admin queries
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsersCreatedAfter = `-- name: CountUsersCreatedAfter :one
SELECT COUNT(*) as total FROM users WHERE created_at >= ?1
`

func (q *Queries) CountUsersCreatedAfter(ctx context.Context, after int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersCreatedAfter, after)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, password_hash, name, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, email, password_hash, name, avatar_url, email_verified,
          email_verify_token, email_verify_expires, password_reset_token,
          password_reset_expires, created_at, updated_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, avatar_url, email_verified,
       email_verify_token, email_verify_expires, password_reset_token,
       password_reset_expires, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER(?1)
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailVerifyToken = `-- name: GetUserByEmailVerifyToken :one
SELECT id, email, password_hash, name, avatar_url, email_verified,
       email_verify_token, email_verify_expires, password_reset_token,
       password_reset_expires, created_at, updated_at
FROM users
WHERE email_verify_token = ?1
  AND email_verify_expires > strftime('%s', 'now')
LIMIT 1
`

func (q *Queries) GetUserByEmailVerifyToken(ctx context.Context, token sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailVerifyToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, avatar_url, email_verified,
       email_verify_token, email_verify_expires, password_reset_token,
       password_reset_expires, created_at, updated_at
FROM users
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPasswordResetToken = `-- name: GetUserByPasswordResetToken :one
SELECT id, email, password_hash, name, avatar_url, email_verified,
       email_verify_token, email_verify_expires, password_reset_token,
       password_reset_expires, created_at, updated_at
FROM users
WHERE password_reset_token = ?1
  AND password_reset_expires > strftime('%s', 'now')
LIMIT 1
`

func (q *Queries) GetUserByPasswordResetToken(ctx context.Context, token sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPasswordResetToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersPaginated = `-- name: ListUsersPaginated :many
SELECT id, email, name, avatar_url, email_verified, created_at, updated_at
FROM users
WHERE (?1 = '' OR LOWER(email) LIKE '%' || LOWER(?1) || '%' OR LOWER(name) LIKE '%' || LOWER(?1) || '%')
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListUsersPaginatedParams struct {
	Search     interface{} `json:"search"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

type ListUsersPaginatedRow struct {
	ID            string         `json:"id"`
	Email         string         `json:"email"`
	Name          string         `json:"name"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	EmailVerified int64          `json:"email_verified"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]ListUsersPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersPaginated, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPaginatedRow
	for rows.Next() {
		var i ListUsersPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users
SET email_verified = 1,
    email_verify_token = NULL,
    email_verify_expires = NULL,
    updated_at = strftime('%s', 'now')
WHERE id = ?1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setEmailVerified, id)
	return err
}

const setEmailVerifyToken = `-- name: SetEmailVerifyToken :exec
UPDATE users
SET email_verify_token = ?1,
    email_verify_expires = ?2,
    updated_at = strftime('%s', 'now')
WHERE id = ?3
`

type SetEmailVerifyTokenParams struct {
	Token   sql.NullString `json:"token"`
	Expires sql.NullInt64  `json:"expires"`
	ID      string         `json:"id"`
}

func (q *Queries) SetEmailVerifyToken(ctx context.Context, arg SetEmailVerifyTokenParams) error {
	_, err := q.db.ExecContext(ctx, setEmailVerifyToken, arg.Token, arg.Expires, arg.ID)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users
SET password_reset_token = ?1,
    password_reset_expires = ?2,
    updated_at = strftime('%s', 'now')
WHERE id = ?3
`

type SetPasswordResetTokenParams struct {
	Token   sql.NullString `json:"token"`
	Expires sql.NullInt64  `json:"expires"`
	ID      string         `json:"id"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, setPasswordResetToken, arg.Token, arg.Expires, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = COALESCE(?1, name),
    avatar_url = COALESCE(?2, avatar_url),
    updated_at = strftime('%s', 'now')
WHERE id = ?3
`

type UpdateUserParams struct {
	Name      sql.NullString `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.AvatarUrl, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?1,
    password_reset_token = NULL,
    password_reset_expires = NULL,
    updated_at = strftime('%s', 'now')
WHERE id = ?2
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
