// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package db

import (
	"context"
	"database/sql"
)

const createUserPreferences = `-- name: CreateUserPreferences :one
INSERT INTO user_preferences (
    user_id, email_notifications, marketing_emails, timezone, language, theme, updated_at
) VALUES (
    ?1, 1, 0, 'UTC', 'en', 'system', strftime('%s', 'now')
)
RETURNING user_id, email_notifications, marketing_emails, timezone, language, theme, updated_at
`

type CreateUserPreferencesRow struct {
	UserID             string `json:"user_id"`
	EmailNotifications int64  `json:"email_notifications"`
	MarketingEmails    int64  `json:"marketing_emails"`
	Timezone           string `json:"timezone"`
	Language           string `json:"language"`
	Theme              string `json:"theme"`
	UpdatedAt          int64  `json:"updated_at"`
}

func (q *Queries) CreateUserPreferences(ctx context.Context, userID string) (CreateUserPreferencesRow, error) {
	row := q.db.QueryRowContext(ctx, createUserPreferences, userID)
	var i CreateUserPreferencesRow
	err := row.Scan(
		&i.UserID,
		&i.EmailNotifications,
		&i.MarketingEmails,
		&i.Timezone,
		&i.Language,
		&i.Theme,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserPreferences = `-- name: DeleteUserPreferences :exec
DELETE FROM user_preferences WHERE user_id = ?1
`

func (q *Queries) DeleteUserPreferences(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserPreferences, userID)
	return err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, email_notifications, marketing_emails, timezone, language, theme, updated_at
FROM user_preferences
WHERE user_id = ?1
LIMIT 1
`

type GetUserPreferencesRow struct {
	UserID             string `json:"user_id"`
	EmailNotifications int64  `json:"email_notifications"`
	MarketingEmails    int64  `json:"marketing_emails"`
	Timezone           string `json:"timezone"`
	Language           string `json:"language"`
	Theme              string `json:"theme"`
	UpdatedAt          int64  `json:"updated_at"`
}

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (GetUserPreferencesRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences, userID)
	var i GetUserPreferencesRow
	err := row.Scan(
		&i.UserID,
		&i.EmailNotifications,
		&i.MarketingEmails,
		&i.Timezone,
		&i.Language,
		&i.Theme,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE user_preferences
SET email_notifications = COALESCE(?1, email_notifications),
    marketing_emails = COALESCE(?2, marketing_emails),
    timezone = COALESCE(?3, timezone),
    language = COALESCE(?4, language),
    theme = COALESCE(?5, theme),
    updated_at = strftime('%s', 'now')
WHERE user_id = ?6
`

type UpdateUserPreferencesParams struct {
	EmailNotifications sql.NullInt64  `json:"email_notifications"`
	MarketingEmails    sql.NullInt64  `json:"marketing_emails"`
	Timezone           sql.NullString `json:"timezone"`
	Language           sql.NullString `json:"language"`
	Theme              sql.NullString `json:"theme"`
	UserID             string         `json:"user_id"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPreferences,
		arg.EmailNotifications,
		arg.MarketingEmails,
		arg.Timezone,
		arg.Language,
		arg.Theme,
		arg.UserID,
	)
	return err
}
